apiVersion: v2
appVersion: latest
dependencies:
- name: library-chart
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
  version: 1.3.0
- enabled: true
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.6
description: NocoDB is an open source NoCode platform that turns any database into
  a smart spreadsheet
home: https://www.nocodb.com/
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/nocodb.png
keyworks:
- Tool
- Data
name: nocodb
sources:
- https://github.com/InseeFrLab/helm-charts-datascience/tree/master/charts/nocodb
- https://hub.docker.com/r/nocodb/nocodb
type: application
version: 1.0.2
