apiVersion: v2
appVersion: '355'
dependencies:
- name: library-chart
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
  version: 1.3.0
description: Fast distributed SQL query engine for big data analytics
home: https://trino.io/
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/trino.png
keywords:
- SQL
- distributed
- python
name: trino
sources:
- https://github.com/trinodb/charts
- https://github.com/trinodb/trino/tree/master/core/docker
type: application
version: 0.1.5
