apiVersion: v2
appVersion: latest
dependencies:
- name: library-chart
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
  version: 1.3.0
description: Apache Jena Fuseki is a SPARQL server.
home: https://jena.apache.org/jena
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/jena.png
keyworks:
- RDF
- Triplestore
- Linked Data
name: jena
sources:
- https://github.com/InseeFrLab/helm-charts-datascience/tree/master/charts/jena
- https://github.com/stain/jena-docker
type: application
version: 0.1.5
