apiVersion: v2
appVersion: latest
dependencies:
- name: library-chart
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
  version: 1.3.0
- enabled: true
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.6
description: CloudBeaver is a light modern web-application for database management.
home: https://cloudbeaver.io/
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/cloudbeaver.png
keyworks:
- Tool
- Data
name: cloudbeaver
sources:
- https://github.com/InseeFrLab/helm-charts-databases/tree/main/charts/cloudbeaver
- https://hub.docker.com/r/dbeaver/cloudbeaver
type: application
version: 1.0.5
